name: bump

on:
  schedule:
    - cron: "0 10 * * *" # Daily at 18:00hrs SGT
  workflow_dispatch:

defaults:
  run:
    # NOTE: Default option does not include `-o pipefail` as documented
    # unless explicitly specifying the `bash` shell.
    # https://github.com/actions/runner/issues/353
    shell: bash

jobs:
  bump:
    name: bump
    runs-on: macos-15
    timeout-minutes: 10
    permissions:
      contents: write       # Required to push commits
      pull-requests: write  # Required to create PRs

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@07a2e10c5e201418f928690f897aaff92cf24d3a # master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      # NOTE: The commit email address should be the canonical no-reply email address
      # used by the `github-actions[bot]` bot user.
      # https://api.github.com/users/github-actions%5Bbot%5D
      # https://github.community/t/github-actions-bot-email-address/17204/6
      - name: Set up git config
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # NOTE: The `brew bump` command is used instead of `brew bump-formula-pr`
      # and `brew bump-cask-pr` because it handles fetching the latest version
      # and operates on all formulae/casks within a tap.
      - name: Bump packages
        env:
          # NOTE: `GITHUB_TOKEN` is intentionally used even though created PRs does
          # not trigger GitHub Action workflows and requires manual rebase. Given
          # that updates are infrequent, the cost of manual rebase is lesser than
          # rotating tokens.
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew bump --open-pr --no-fork --tap loozhengyuan/tap
